name: Azure AKS Monitor

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *"

jobs:
  aks-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Azure CLI
        uses: elstudio/action-install-azure-cli@v1
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}
      - name: Get AKS cluster information
        run: |
          aks_cluster_info=$(az aks show --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
          aks_cluster_version=$(echo $aks_cluster_info | jq -r '.kubernetesVersion')
          aks_cluster_upgrades=$(az aks get-upgrades --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
      - name: Get available patches
        run: |
          available_patches=$(echo $aks_cluster_upgrades | jq -r '.upgrades[] | select(.isPreview==false) | .name')
          echo "Available patches: $available_patches"
      - name: Get available revisions
        run: |
          available_revisions=$(az aks get-versions --location ${{ secrets.LOCATION }} --output json | jq -r '.orchestrators[] | select(.isPreview==false) | .orchestratorVersion')
          echo "Available revisions: $available_revisions"
