name: MS-Teams-Webhook

on:
  workflow_dispatch:


jobs:
  job1: 
    runs-on: ubuntu-latest
    outputs:
      clusterInfo: ${{ steps.vers.outputs.kubeVer }}
      patchInfo: ${{ steps.patch.outputs.kubePatch }}
      revisionInfo: ${{ steps.revs.outputs.kubeRevs }}
      
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Azure CLI
        uses: elstudio/action-install-azure-cli@v1
        
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}
          
      - name: Install JQ into Runner
        run: |
          sudo apt-get update
          sudo apt-get install jq
          jq
          
      - name: Get AKS cluster information
        id: vers
        run: |
          aks_cluster_info=$(az aks show --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
          aks_cluster_version=$(echo $aks_cluster_info | jq -r '.kubernetesVersion')
          curVer=$( echo "Current Kubernetes Version: $aks_cluster_version")
          echo $curVer
          echo kubeVer=$curVer >> $GITHUB_OUTPUT
          
      - name: Get available patches
        id: patch
        run: |
          aks_cluster_upgrades=$(az aks get-upgrades --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
          available_patches=$(echo $aks_cluster_upgrades | jq -r '.controlPlaneProfile.upgrades[]')
          echo "Available patches: $available_patches"
          echo kubePatch=$available_patches >> $GITHUB_OUTPUT
          
      - name: Get available revisions
        id: revs
        run: |
          available_revisions=$(az aks get-versions --location ${{ secrets.LOCATION }} --output json | jq -r '.orchestrators[]')
          echo "Available revisions: $available_revisions"
          echo kubeRevs=$available_revisions >> $GITHUB_OUTPUT
  
  job2: 
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          KVER: ${{needs.job1.outputs.clusterInfo}}
          PATCH: ${{needs.job1.outputs.kubePatch}}
          REV: ${{needs.job1.outputs.kubeRevs}}
      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: 'Kubernetes Cluster Updates'
          summary: 'Patch Information'
          text: '$KVER '
