name: MS Teams Webhook
on:
  workflow_dispatch:
jobs:
  acquire-kubernetes-data: 
    runs-on: ubuntu-latest
    outputs:
      clusterInfo: ${{ steps.vers.outputs.kubeVer }}
      patchInfo: ${{ steps.patch.outputs.kubePatch }}
      revisionInfo: ${{ steps.revs.outputs.kubeRevs }}
      
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Azure CLI
        uses: elstudio/action-install-azure-cli@v1
        
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}
          
      - name: Install JQ into Runner
        run: |
          sudo apt-get update
          sudo apt-get install jq
          jq
          
      - name: Get AKS cluster information
        id: vers
        run: |
          aks_cluster_info=$(az aks show --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
          aks_cluster_version=$(echo $aks_cluster_info | jq -r '.kubernetesVersion')
          echo kubeVer=$( echo "Current Kubernetes Version: $aks_cluster_version") >> $GITHUB_ENV
          
      - name: Get available patches
        id: patch
        run: |
          aks_cluster_upgrades=$(az aks get-upgrades --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --output json)
          availablepatches=$(echo $aks_cluster_upgrades | jq -r '.controlPlaneProfile.upgrades[]')
          echo kubePatch=availablepatches >> $GITHUB_ENV
          
      - name: Get available revisions
        id: revs
        run: |
          availablerevisions=$(az aks get-versions --location ${{ secrets.LOCATION }} --output json | jq -r '.orchestrators[]')
          echo kubeRevs=$availablerevisions >> $GITHUB_ENV

      - name: 📣 Send teams notification
        uses: simbo/msteams-message-card-action@latest
        env:
          RELEASE_BUTTON: AKS-Releases https://releases.aks.azure.com/
          ISSUES_BUTTON: AKS-Issues https://github.com/Azure/AKS/issues
          MESSAGEOUT: 'This will work'
        with:
          webhook:  ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: ${{env.kubeVer}}
          message: |
           Upgrade Opportunities for: ${{env.kubeVer}}
           Patches:
           ${{env.kubePatch}}
           Revision Upgrade Path:
           ${{env.kubeRevs}}
          color: ff69b4
          buttons: |
            ${{ env.ISSUES_BUTTON }}
            ${{ env.RELEASE_BUTTON }}
  
